package com.kalyan.util

fun getCompaniesAndLines() = mapOf(
    "Satyr" to listOf("No Flavors", "Dokha", "Brilliant Collection", "Aroma Line", "Platinum Collection"),
    "Al Fakher" to listOf("Основная", "Base"),
    "Tangiers" to listOf("Noir", "F-Line", "Burley", "Birquq", "Special Edition"),
    "Северный" to listOf("Основная", "Professional"),
    "Naш (Наш)" to listOf("Основная", "Крепкая"),
    "Хулиган" to listOf("Стандартная", "Крепкая"),
    "Сарма" to listOf("Основная", "Сарма 360"),
    "Bonche" to listOf("Основная", "Линейка 5%"),
    "Must Have" to listOf("Основная"),
    "Duft" to listOf("Solo", "Checkmate", "Pheromone", "Morgenshtern", "Cobra", "Intro", "The Hatters", "Strong", "All-in"),
    "Jam" to listOf("Основная"),
    "Smoke Angels" to listOf("Основная"),
    "Mattpear" to listOf("Основная", "Old School", "Crazy", "Pop"),
    "Black Burn" to listOf("Основная"),
    "Sebero" to listOf("Основная", "Limited Edition", "Arctic Mix", "Black"),
    "Cobra" to listOf("La Muerte", "Virgin", "Origins", "Select"),
    "Spectrum" to listOf("Classic Line", "Hard Line", "Mix Line", "Kitchen Line"),
    "Chabacco" to listOf("Medium", "Strong", "Chabacco MIX", "JohnCalliano Fest", "Hookahplace", "Gastro", "Emotions"),
    "Element" to listOf("Вода", "Земля", "Воздух", "Огонь", "V Element"),
    "Daily Hookah" to listOf("Основная"),
    "Starline" to listOf("Ягоды", "Фрукты", "Десерты", "Напитки", "Другое"),
    "Darkside" to listOf("Base", "Core", "Rare", "Shot"),
    "Brusko" to listOf("Medium (чайная смесь)", "BIT", "Strong (чайная смесь)", "Hookah (табак)"),
    "Adalya" to listOf("Основная", "Black"),
    "Banger" to listOf("Основная"),
    "Afzal" to listOf("Основная", "Strong"),
)
